version: 2

models:
    - name: l2
      description: "Returns Data across all customers"
      columns:
          - name: RETURNID
            description: "Flag to understand if order is returned or not"
            tests:
                - unique
                - not_null
          - name: ORDERID
            description: "Order returned"
            tests:
                - not_null


    